"""initial_schema_25_tables

Revision ID: f3581f07aaab
Revises: 
Create Date: 2026-09-26 22:18:15.258755
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3581f07aaab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_agents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('developer', sa.String(length=128), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('credit_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index('idx_a2a_agents_credit_level', 'a2a_agents', ['credit_level'], unique=False)
    op.create_index('idx_a2a_agents_status', 'a2a_agents', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('autonomy_level', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('system_prompt_text', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_autonomy_level', 'agents', ['autonomy_level'], unique=False)
    op.create_index('idx_agents_role', 'agents', ['role'], unique=False)
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index('uk_agents_business_id', 'agents', ['business_id'], unique=True, postgresql_where="status != 'stopped'")
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=32), nullable=True),
    sa.Column('business_model', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_businesses_category', 'businesses', ['category'], unique=False)
    op.create_index('idx_businesses_deleted_at', 'businesses', ['deleted_at'], unique=False)
    op.create_index('idx_businesses_owner_id', 'businesses', ['owner_id'], unique=False)
    op.create_index('idx_businesses_status', 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_uuid'), 'businesses', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_index('uk_users_email', 'users', ['email'], unique=True, postgresql_where='email IS NOT NULL AND deleted_at IS NULL')
    op.create_index('uk_users_phone', 'users', ['phone'], unique=True, postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.create_table('a2a_gateway_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_agent_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_a2a_gw_logs_biz_created', 'a2a_gateway_logs', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_a2a_gw_logs_created_at', 'a2a_gateway_logs', ['created_at'], unique=False)
    op.create_index('idx_a2a_gw_logs_external_created', 'a2a_gateway_logs', ['external_agent_id', 'created_at'], unique=False)
    op.create_index('idx_a2a_gw_logs_request_hash', 'a2a_gateway_logs', ['request_hash'], unique=False)
    op.create_index('idx_a2a_gw_logs_status_code', 'a2a_gateway_logs', ['status_code'], unique=False)
    op.create_table('a2a_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_agent_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('session_status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_a2a_sessions_business_id', 'a2a_sessions', ['business_id'], unique=False)
    op.create_index('idx_a2a_sessions_external_biz', 'a2a_sessions', ['external_agent_id', 'business_id'], unique=False)
    op.create_index('idx_a2a_sessions_status_created', 'a2a_sessions', ['session_status', 'created_at'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('memory_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memories_agent_importance', 'agent_memories', ['agent_id', 'importance'], unique=False)
    op.create_index('idx_agent_memories_agent_type_created', 'agent_memories', ['agent_id', 'memory_type', 'created_at'], unique=False)
    op.create_index('idx_agent_memories_source', 'agent_memories', ['source', 'source_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('context_summary', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_sessions_agent_status', 'agent_sessions', ['agent_id', 'status'], unique=False)
    op.create_index('idx_agent_sessions_biz_created', 'agent_sessions', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_agent_sessions_session_type', 'agent_sessions', ['session_type'], unique=False)
    op.create_table('agent_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('installed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_skills_status', 'agent_skills', ['status'], unique=False)
    op.create_index('uk_agent_skills_agent_skill_key', 'agent_skills', ['agent_id', 'skill_key'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('idx_alerts_biz_created', 'alerts', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_biz_status_level', 'alerts', ['business_id', 'status', 'level'], unique=False)
    op.create_index('idx_alerts_level', 'alerts', ['level'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('log_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_logs_biz_created', 'audit_logs', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('circuit_breaks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('trigger_condition', sa.String(length=128), nullable=False),
    sa.Column('trigger_value', sa.Numeric(), nullable=True),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_by', sa.BigInteger(), nullable=True),
    sa.Column('recovery_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_circuit_breaks_biz_status', 'circuit_breaks', ['business_id', 'status'], unique=False)
    op.create_index('idx_circuit_breaks_created_at', 'circuit_breaks', ['created_at'], unique=False)
    op.create_index('idx_circuit_breaks_level_created', 'circuit_breaks', ['level', 'created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_biz_last_order', 'customers', ['business_id', 'last_order_at'], unique=False)
    op.create_index('idx_customers_biz_level', 'customers', ['business_id', 'level'], unique=False)
    op.create_index('idx_customers_deleted_at', 'customers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=True)
    op.create_index('uk_customers_biz_phone', 'customers', ['business_id', 'phone'], unique=True, postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_business_id_category', 'products', ['business_id', 'category'], unique=False)
    op.create_index('idx_products_business_id_status', 'products', ['business_id', 'status'], unique=False)
    op.create_index('idx_products_deleted_at', 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('user_business_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_biz_roles_biz_role', 'user_business_roles', ['business_id', 'role'], unique=False)
    op.create_index('idx_user_biz_roles_status', 'user_business_roles', ['status'], unique=False)
    op.create_index('idx_user_biz_roles_user_id', 'user_business_roles', ['user_id'], unique=False)
    op.create_index('uk_user_biz_roles_user_biz', 'user_business_roles', ['user_id', 'business_id'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('expected_effect', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitter_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('approver_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_orders_agent_created', 'work_orders', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_work_orders_biz_status', 'work_orders', ['business_id', 'status'], unique=False)
    op.create_index('idx_work_orders_order_type', 'work_orders', ['order_type'], unique=False)
    op.create_index('idx_work_orders_risk_level', 'work_orders', ['risk_level'], unique=False)
    op.create_index('idx_work_orders_status_created', 'work_orders', ['status', 'created_at'], unique=False)
    op.create_table('a2a_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('a2a_session_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('response_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['a2a_session_id'], ['a2a_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_a2a_messages_direction', 'a2a_messages', ['direction'], unique=False)
    op.create_index('idx_a2a_messages_message_type', 'a2a_messages', ['message_type'], unique=False)
    op.create_index('idx_a2a_messages_session_created', 'a2a_messages', ['a2a_session_id', 'created_at'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_messages_agent_created', 'agent_messages', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_agent_messages_role', 'agent_messages', ['role'], unique=False)
    op.create_index('idx_agent_messages_session_created', 'agent_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('modified_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_actions_action', 'approval_actions', ['action'], unique=False)
    op.create_index('idx_approval_actions_approver', 'approval_actions', ['approver_id'], unique=False)
    op.create_index('idx_approval_actions_work_order_created', 'approval_actions', ['work_order_id', 'created_at'], unique=False)
    op.create_table('execution_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id')
    )
    op.create_index('idx_execution_jobs_agent_created', 'execution_jobs', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_execution_jobs_biz_status', 'execution_jobs', ['business_id', 'status'], unique=False)
    op.create_index('idx_execution_jobs_status', 'execution_jobs', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(), nullable=False),
    sa.Column('payable_amount', sa.Numeric(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_orders_biz_created', 'orders', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_orders_business_id_status', 'orders', ['business_id', 'status'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('idx_orders_deleted_at', 'orders', ['deleted_at'], unique=False)
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=True)
    op.create_table('skus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('spec_name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('cost_price', sa.Numeric(), nullable=True),
    sa.Column('original_price', sa.Numeric(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_index('idx_skus_barcode', 'skus', ['barcode'], unique=False)
    op.create_index('idx_skus_business_id_status', 'skus', ['business_id', 'status'], unique=False)
    op.create_index('idx_skus_deleted_at', 'skus', ['deleted_at'], unique=False)
    op.create_index('idx_skus_product_id', 'skus', ['product_id'], unique=False)
    op.create_index('idx_skus_stock_qty', 'skus', ['stock_qty'], unique=False)
    op.create_index(op.f('ix_skus_uuid'), 'skus', ['uuid'], unique=True)
    op.create_table('inventory_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('in_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('in_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_index('idx_inventory_batches_biz_sku', 'inventory_batches', ['business_id', 'sku_id'], unique=False)
    op.create_index('idx_inventory_batches_expire_date', 'inventory_batches', ['expire_date'], unique=False)
    op.create_index('idx_inventory_batches_status', 'inventory_batches', ['status'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('before_qty', sa.Integer(), nullable=False),
    sa.Column('after_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_type', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_logs_biz_sku_created', 'inventory_logs', ['business_id', 'sku_id', 'created_at'], unique=False)
    op.create_index('idx_inventory_logs_change_type', 'inventory_logs', ['change_type'], unique=False)
    op.create_index('idx_inventory_logs_operator', 'inventory_logs', ['operator_type', 'operator_id'], unique=False)
    op.create_index('idx_inventory_logs_ref', 'inventory_logs', ['ref_type', 'ref_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('sku_spec', sa.String(length=128), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('discount', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_biz_sku', 'order_items', ['business_id', 'sku_id'], unique=False)
    op.create_index('idx_order_items_business_id', 'order_items', ['business_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###

    # 所有表创建后添加外键约束（解决表间循环依赖）
    op.create_foreign_key('fk_agents_business_id', 'agents', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_businesses_agent_id', 'businesses', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_businesses_owner_id', 'businesses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('fk_a2a_gateway_logs_business_id', 'a2a_gateway_logs', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_a2a_gateway_logs_external_agent_id', 'a2a_gateway_logs', 'a2a_agents', ['external_agent_id'], ['id'])
    op.create_foreign_key('fk_a2a_sessions_business_id', 'a2a_sessions', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_a2a_sessions_external_agent_id', 'a2a_sessions', 'a2a_agents', ['external_agent_id'], ['id'])
    op.create_foreign_key('fk_agent_memories_agent_id', 'agent_memories', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_agent_memories_business_id', 'agent_memories', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_agent_sessions_agent_id', 'agent_sessions', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_agent_sessions_business_id', 'agent_sessions', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_alerts_business_id', 'alerts', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_audit_logs_business_id', 'audit_logs', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_circuit_breaks_business_id', 'circuit_breaks', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_customers_business_id', 'customers', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_products_business_id', 'products', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_work_orders_agent_id', 'work_orders', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_work_orders_business_id', 'work_orders', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_work_orders_submitter_agent_id', 'work_orders', 'agents', ['submitter_agent_id'], ['id'])
    op.create_foreign_key('fk_agent_messages_agent_id', 'agent_messages', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_execution_jobs_agent_id', 'execution_jobs', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key('fk_execution_jobs_business_id', 'execution_jobs', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_execution_jobs_work_order_id', 'execution_jobs', 'work_orders', ['work_order_id'], ['id'])
    op.create_foreign_key('fk_orders_business_id', 'orders', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_orders_customer_id', 'orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('fk_skus_business_id', 'skus', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_skus_product_id', 'skus', 'products', ['product_id'], ['id'])
    op.create_foreign_key('fk_inventory_batches_business_id', 'inventory_batches', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_inventory_batches_sku_id', 'inventory_batches', 'skus', ['sku_id'], ['id'])
    op.create_foreign_key('fk_inventory_logs_business_id', 'inventory_logs', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_inventory_logs_sku_id', 'inventory_logs', 'skus', ['sku_id'], ['id'])
    op.create_foreign_key('fk_order_items_business_id', 'order_items', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('fk_order_items_sku_id', 'order_items', 'skus', ['sku_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_business_id', table_name='order_items')
    op.drop_index('idx_order_items_biz_sku', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_inventory_logs_ref', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_operator', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_change_type', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_biz_sku_created', table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index('idx_inventory_batches_status', table_name='inventory_batches')
    op.drop_index('idx_inventory_batches_expire_date', table_name='inventory_batches')
    op.drop_index('idx_inventory_batches_biz_sku', table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_skus_uuid'), table_name='skus')
    op.drop_index('idx_skus_stock_qty', table_name='skus')
    op.drop_index('idx_skus_product_id', table_name='skus')
    op.drop_index('idx_skus_deleted_at', table_name='skus')
    op.drop_index('idx_skus_business_id_status', table_name='skus')
    op.drop_index('idx_skus_barcode', table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.drop_index('idx_orders_payment_status', table_name='orders')
    op.drop_index('idx_orders_deleted_at', table_name='orders')
    op.drop_index('idx_orders_customer_id', table_name='orders')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_business_id_status', table_name='orders')
    op.drop_index('idx_orders_biz_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_execution_jobs_status', table_name='execution_jobs')
    op.drop_index('idx_execution_jobs_biz_status', table_name='execution_jobs')
    op.drop_index('idx_execution_jobs_agent_created', table_name='execution_jobs')
    op.drop_table('execution_jobs')
    op.drop_index('idx_approval_actions_work_order_created', table_name='approval_actions')
    op.drop_index('idx_approval_actions_approver', table_name='approval_actions')
    op.drop_index('idx_approval_actions_action', table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index('idx_agent_messages_session_created', table_name='agent_messages')
    op.drop_index('idx_agent_messages_role', table_name='agent_messages')
    op.drop_index('idx_agent_messages_agent_created', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('idx_a2a_messages_session_created', table_name='a2a_messages')
    op.drop_index('idx_a2a_messages_message_type', table_name='a2a_messages')
    op.drop_index('idx_a2a_messages_direction', table_name='a2a_messages')
    op.drop_table('a2a_messages')
    op.drop_index('idx_work_orders_status_created', table_name='work_orders')
    op.drop_index('idx_work_orders_risk_level', table_name='work_orders')
    op.drop_index('idx_work_orders_order_type', table_name='work_orders')
    op.drop_index('idx_work_orders_biz_status', table_name='work_orders')
    op.drop_index('idx_work_orders_agent_created', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index('uk_user_biz_roles_user_biz', table_name='user_business_roles')
    op.drop_index('idx_user_biz_roles_user_id', table_name='user_business_roles')
    op.drop_index('idx_user_biz_roles_status', table_name='user_business_roles')
    op.drop_index('idx_user_biz_roles_biz_role', table_name='user_business_roles')
    op.drop_table('user_business_roles')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index('idx_products_deleted_at', table_name='products')
    op.drop_index('idx_products_business_id_status', table_name='products')
    op.drop_index('idx_products_business_id_category', table_name='products')
    op.drop_table('products')
    op.drop_index('uk_customers_biz_phone', table_name='customers', postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_index('idx_customers_deleted_at', table_name='customers')
    op.drop_index('idx_customers_biz_level', table_name='customers')
    op.drop_index('idx_customers_biz_last_order', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_circuit_breaks_level_created', table_name='circuit_breaks')
    op.drop_index('idx_circuit_breaks_created_at', table_name='circuit_breaks')
    op.drop_index('idx_circuit_breaks_biz_status', table_name='circuit_breaks')
    op.drop_table('circuit_breaks')
    op.drop_index('idx_audit_logs_target', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_biz_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_alerts_level', table_name='alerts')
    op.drop_index('idx_alerts_biz_status_level', table_name='alerts')
    op.drop_index('idx_alerts_biz_created', table_name='alerts')
    op.drop_index('idx_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('uk_agent_skills_agent_skill_key', table_name='agent_skills')
    op.drop_index('idx_agent_skills_status', table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_index('idx_agent_sessions_session_type', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_biz_created', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_agent_status', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('idx_agent_memories_source', table_name='agent_memories')
    op.drop_index('idx_agent_memories_agent_type_created', table_name='agent_memories')
    op.drop_index('idx_agent_memories_agent_importance', table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index('idx_a2a_sessions_status_created', table_name='a2a_sessions')
    op.drop_index('idx_a2a_sessions_external_biz', table_name='a2a_sessions')
    op.drop_index('idx_a2a_sessions_business_id', table_name='a2a_sessions')
    op.drop_table('a2a_sessions')
    op.drop_index('idx_a2a_gw_logs_status_code', table_name='a2a_gateway_logs')
    op.drop_index('idx_a2a_gw_logs_request_hash', table_name='a2a_gateway_logs')
    op.drop_index('idx_a2a_gw_logs_external_created', table_name='a2a_gateway_logs')
    op.drop_index('idx_a2a_gw_logs_created_at', table_name='a2a_gateway_logs')
    op.drop_index('idx_a2a_gw_logs_biz_created', table_name='a2a_gateway_logs')
    op.drop_table('a2a_gateway_logs')
    op.drop_index('uk_users_phone', table_name='users', postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.drop_index('uk_users_email', table_name='users', postgresql_where='email IS NOT NULL AND deleted_at IS NULL')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_uuid'), table_name='businesses')
    op.drop_index('idx_businesses_status', table_name='businesses')
    op.drop_index('idx_businesses_owner_id', table_name='businesses')
    op.drop_index('idx_businesses_deleted_at', table_name='businesses')
    op.drop_index('idx_businesses_category', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index('uk_agents_business_id', table_name='agents', postgresql_where="status != 'stopped'")
    op.drop_index('idx_agents_status', table_name='agents')
    op.drop_index('idx_agents_role', table_name='agents')
    op.drop_index('idx_agents_autonomy_level', table_name='agents')
    op.drop_table('agents')
    op.drop_index('idx_a2a_agents_status', table_name='a2a_agents')
    op.drop_index('idx_a2a_agents_credit_level', table_name='a2a_agents')
    op.drop_table('a2a_agents')
    # ### end Alembic commands ###
